### ISSUE TITLE
Milliseconds are invalid VTT

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [aguang-xyz/auto-caption#4]
I as using this to add subtitiles to my online lecture. However I was unable to add them into our insititutions transcript editor, with it complaining about a bad format. I ran the VTT generated here though an online VTT validator [here](https://quuz.org/webvtt/) and learned that miliseconds should be 3 digits long.

Just changing this line

https://github.com/aguang-xyz/auto-caption/blob/d36acf7cc264543baad95c7745d22bdbc22177c8/auto_caption/__init__.py#L161-L167

To the following seems to fix this millisecond issue.

```python
def time2str_vtt(x):

    return "{hour:02d}:{minute:02d}:{second:02d}.{millisecond:03d}".format(
        hour=int(x) // 3600,
        minute=(int(x) // 60) % 60,
        second=int(x) % 60,
        millisecond=int(x * 1000) % 1000)
```

**Comment by aguang-xyz** [comment]
@QuantumEntangledAndy Nice, thanks for your contribution to this project. Would you mind to submit a PR for this?
